### ISSUE TITLE
Add description mandate in Fedvoc

### ISSUE THREAD

**Issue by smals-vea** [belgif/fedvoc#1]
Proposition :
•	Mandat / mandaat / mandate 
•	Mandataire / mandataris / authorised representative
•	Mandant/ mandaatgever / mandator

Diverses recherches :

1.	Glossaire : fr : Mandat / nl : mandaat / 
Wordreference : en : mandate or authoris(z)ation

2.	Glossaire : fr : Mandataire / nl : mandataris / 
Wordreference   : en : authoris(z)ed representative

3.	Wordreference  : fr: Mandant / en : mandator
IATE : en : principal
Site Sécurité sociale : nl : mandaatgever

https://wwwacc.socialsecurity.be/site_nl/employer/applics/mahis/general/what_mandate.htm
https://wwwacc.socialsecurity.be/site_fr/employer/applics/mahis/general/what_mandate.htm

•	Un mandant : l’entité qui délivre le mandat à une autre entité. Le mandant doit être identifié de façon univoque dans une source authentique.
•	Un mandataire : l’entité qui reçoit le mandat d’une autre entité. Le mandataire doit être identifié de façon univoque dans une source authentique.
•	Un objet de mandat : le(s) groupe(s) d'applications de sécurité sociale auquel (auxquels) se rapporte le mandat.
•	Une période de validité : un trimestre de début et un trimestre de fin (optionnel).
•	Un statut : détermine le statut du mandat dans le système (actif, clos…).

•	Een mandaatgever: de entiteit die een mandaat geeft aan een andere entiteit. De mandaatgever moet eenduidig geïdentificeerd zijn in een authentieke bron.
•	Een mandataris: de entiteit die een mandaat ontvangt van een andere entiteit. De mandataris moet eenduidig geïdentificeerd zijn in een authentieke bron.
•	Een mandaatvoorwerp: de groep of groepen van toepassingen van de sociale zekerheid waarvoor het mandaat geldt.
•	Een geldigheidsperiode: een beginkwartaal en een eindkwartaal (optioneel).
•	Een status: bepaalt de status van een mandaat in het systeem (actief, gesloten...).

**Comment by MarcBruyland** [comment]
https://www.socialsecurity.be/site_nl/employer/applics/mahis/general/what_mandate.htm
https://www.socialsecurity.be/site_fr/employer/applics/mahis/general/what_mandate.htm

**Comment by smals-vea** [comment]
Validation selon 
<http://www.w3.org/ns/org#Mandate>:
• Mandat / mandaat / mandate

<http://www.w3.org/ns/org#mandatary>
• Mandataire / mandataris / **mandatary**

<http://www.w3.org/ns/org#mandator>
• Mandant/ mandaatgever / mandator

**Comment by smals-vea** [comment]
Est-ce que ces concepts doivent être classés dans "generic" ou dans "organization" ?

**Comment by smals-vea** [comment]
30/07/2021: le groupe a décidé de retirer de FedVoc "mandataryRepresentative" car ce 4ème concept n'est pas connu chez Mahis.
Rappel: mandataryRepresentative est la personne physique qui représente un "mandatary"

@MarcBruyland , va vérifier si ce concept est utilisé chez BOSA

**Comment by smals-vea** [comment]
Est-ce que ces concepts doivent être classés dans "generic" ou dans "organization" ?

**Comment by MarcBruyland** [comment]
A mandate can be given to both a person and an organization.
