### ISSUE TITLE
Update definition of provisionalNssoNumber in FedVoc

### ISSUE THREAD

**Issue by smals-vea** [belgif/fedvoc#11]
@MarcBruyland kan je de update van de beschrijving (EN, NL, FR) doen, aub ?

id 694: provisionalNssoNumber:

EN: 
Provisional number assigned by the NSSO to new employers awaiting a definitive NSSO number or to employers hiring only workers who are not subject to social security (DAC workers (Third Employment Circuit), 
A17...), excluding "small statutes”.
Integer and element of [5000000120;5999999989]

NL: 
Tijdelijk nummer toegekend door de RSZ aan nieuwe werkgevers in afwachting van een definitief RSZ-nummer of aan werkgevers die alleen werknemers aanwerven die niet aan de sociale zekerheid onderworpen zijn (DAC-werknemers (Derde Arbeidscircuit), A17…), buiten de “kleine statuten”.
Geheel getal en element van [5000000120;5999999989]

FR:
Numéro provisoire attribué par l’ONSS aux nouveaux employeurs en attente d’un numéro ONSS définitif ou aux employeurs n’engageant que des travailleurs non-assujetti à la sécurité sociale (travailleurs TCT (Troisième Circuit de Travail), A17, …), hors « petits statuts ».
Nombre entier et élément de [5000000120;5999999989]

**Comment by MarcBruyland** [comment]
Issue is closed as decided by the functional workgroup meeting of 2021-01-29.
