### ISSUE TITLE
names of government organizations

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#12]
Standardize naming of government organizations that are often used in web services.

For regional organizations (other than Brussels), we could use the language of the region.

For federal or Brussels organizations, a language-agnostic or English name is not always defined.
At CBSS, we use a language-agnostic abbreviation (e.g. SFPD, Actiris, Fedris) if it exists, and define one based on an English name if it doesn't.

* OCMW - CPAS
  * NL: Openbaar centrum voor maatschappelijk welzijn (OCMW), FR: Centre public d'action sociale (CPAS) and DE: Öffentliches Sozialhilfezentrum (ÖSHZ).
  * EN: multiple formats
    * PCSA: "Public Center of Social Action" or "Public Central of Social Aid" - used by CBSS and [CPAS Woluwe](https://www.woluwe1150.be/en/municipal-services/affaires-sociales-en/cpas-en/)
    * PCSW:  Public Center for Social Welfare - used by Smals and [wikipedia](https://en.wikipedia.org/wiki/Public_Centre_for_Social_Welfare) and [MI-IS website](https://www.mi-is.be/en)
    * Public Welfare Center - [Brussels](https://www.brussels.be/public-welfare-centre-cpas-ocmw-brussels)
    * Public Social Welfare Center on [belgium.be](https://www.belgium.be/en/family/social_security_in_belgium) 
* nsso, cbss, bosa, sigedis, fedris => I think we can just add these to vocabularies
* SFPD - federale pensioendienst - service fédérale de pensions
* RVA/ONEM - EN: NEO?
* NR/RN => rrn?
* RSVZ/INASTI => EN = NISSE (official)

**Comment by smals-vea** [comment]
nsso, cbss, bosa, sigedis, fedris => I think we can just add these to vocabularies and also cbe
RVA/ONEM - EN: NEO? NEO is inderdaad bij Smals gebruiken

**Comment by pvdbosch** [comment]
@MarcBruyland will add sheet to Excel with organization list, with short name (language neutral) + full name (3 languages)

**Comment by pvdbosch** [comment]
The list was already added apparently, but we forget about it.

Suggested modifications:
* add column with validation status (draft/standard)
* merge ONEM/RVA/LfA into a single row  NEO (National Employment Office)  
* RRN : EN - National Registry

**Comment by smals-vea** [comment]
More institutions see on: https://www.smals.be/nl/content/ledenlijst

**Comment by smals-vea** [comment]
@MarcBruyland, lors de notre réunion du 30/07/2021, il a été décidé que RRN devait être retiré de la liste des institutions. Par contre, sur base du lien envoyé ci-dessus, on pourrait encore compléter la liste.

**Comment by pvdbosch** [comment]
I'll propose additions in the fedvoc format for nsso, cbss, bosa, sigedis and fedris. @smals-vea if you have others you want to add based on the Smals ledenlijst, you can propose them in this issue as well.

**Comment by pvdbosch** [comment]
Proposed additions, compiled from their websites and KBO public search:

| Code | EN | NL | FR | DE|
|---|---|---|---|---|
|NSSO | NSSO = National Social Security Office | RSZ = Rijksdienst voor Sociale Zekerheid | ONSS = Office National de Sécurité Sociale | LSS = Landesamt für Soziale Zicherheit|
|CBSS | CBSS = Crossroads Bank of Social Security | KSZ = Kruispuntbank van de Sociale Zekerheid | BCSS = Banque-Carrefour de la Sécurité Sociale| ZDSS = Zentrale Datenbank der sozialen Sicherheit|
|BOSA | Federal Public Service Policy and Support (BOSA) | Federale Overheidsdienst Beleid en Ondersteuning (BOSA) | Service Public Fédéral Stratégie et Appui | Föderaler Öffentlichter Dienst Politik und Unterstützung (BOSA)|
|Sigedis | Sigedis | Sociale Individuele Gegevens  (Sigedis)| Données Individuelles Sociales (Sigedis) |Sigedis |
|Fedris | Fedris | Federaal agentschap voor beroepsrisico's (Fedris) | Agence fédérale des risques professionnels (Fedris) | Föderalagentur für berufsrisiken (Fedris)|

**Comment by pvdbosch** [comment]
Suggested to change English for RJV/ONVA: NOAV = National Office for Annual Vacation. There is no official translation, but already unofficially in use internally at RJV/ONVA and CBSS.

**Comment by MarcBruyland** [comment]
Proposal of Peter was accepted. Issue can be closed.
