### ISSUE TITLE
international address

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#14]
Current types in fedvoc are based on Belgian address structure.
Can we create a more generic international address?

Considerations: 
* city vs municipality
* Some address fields may not exist in each country

**Comment by smals-vea** [comment]
Lors de la réunion du 30/7/2021, il est apparu que les définitions européennes n'étaient pas claires et le mapping avec BestAddress pas évident.
Exemples: 

- locatorDesignator contiendrait houseNumber et boxNumber
- locatorName est plutôt pour préciser un local (de réunion, ...)
- postCode serait bien équivalent à postCode (de Best)
- postName par contre ne contient que la commune liée à postCode et pas un string de plusieurs communes comme c'est le cas pour le postName BestAddress des régions flamande et bruxelloise
- thoroughfare serait l'équivalent de streetName mais la définition est plus large car peut être aussi un canal
- locality ? municipalityName ? town?
- addressArea ? partOfMunicipality ? city area? village?

**@MarcBruyland , éclaircir les définitions des adresses européennes et celles de BestAddress**

Remarque: chez eHealth, ils suivent le standard FHIR pour:

- postalCode
- city
- district
- state
- country (iso alpha2 ou iso alpha3)

mais ont défini:

- streetName
- houseNumber
- postBox (pour boxNumber Best)

**Comment by MarcBruyland** [comment]
An address according to European standards, is referred to in the ICEG standard on Public Organizations:
https://belgif.github.io/thematic/models/public%20organisation/index_en.html

**Comment by MarcBruyland** [comment]
# Belgian address 
see fedvoc https://github.com/belgif/fedvoc

municipalityName
postCode
partOfMunicipalityName     (Wallonia only)
postName                            (Brussels and Flanders only)
streetName
homonymAddition              (Flanders only)
houseNumber
boxNumber
hasRepresentation               

Proposal for filling in hasRepresentation:
"streetname (homonymAddition), houseNumber, boxNumber
postCode, municipalityName"
(homonymAddition for Flemish address only if there is one, which is very rare)

# International address:
see https://belgif.github.io/thematic/models/public%20organisation/index_en.html#Address

address area 
address ID
administrative unit level 1 (country)
administrative unit level 2 (country/region/state)
full address
locator designator
locator name
post code
post name (city)
post office box
thoroughfare


# Mapping from Belgian address to International address:

municipalityName                                                 to post name (city)
postCode                                                               to post code
partOfMunicipalityName                                       -
postName                                                              -
streetName + homonymAddition                         to thoroughfare
houseNumber + boxNumber                                to locator designator
hasRepresentation                                                 to full address

**Comment by smals-vea** [comment]
@MarcBruyland mogen we niet 

- partOfMunicipalityName -
- postName -
ook to post name (city) zetten ?

**Comment by MarcBruyland** [comment]
If we want to map a BEST address to an international address, we have all data related to the address at hand (municipality name, postcode, eventual postName, eventual partOfMunicipalityName). The data element that is then most fit to be mapped on post name (city) is the municipality name.

**Comment by smals-vea** [comment]
Documented by @MarcBruyland on the Wiki: https://github.com/belgif/fedvoc/wiki/Mapping-of-a-Belgian-(BEST)-address-on-an-international-address
