### ISSUE TITLE
Auth.source Country-services

### ISSUE THREAD

**Issue by MarcBruyland** [belgif/fedvoc#15]
## Context 
BOSA is going to provide REST services besides already existing SOAP services.

## Datamodel of the A.S.
![CountryServices](https://user-images.githubusercontent.com/20465494/115244793-9378e380-a124-11eb-8320-c70f24ff0b9b.png)

## REST URLs proposed to REST styleguide workgroup:
GET /REST/countries/v1/isoCodes?referenceDate=
GET /REST/countries/v1/nisCodes?referenceDate= 

GET /REST/nationalities/v1/nationality?isoAlpha2= ,
GET /REST/nationalities/v1/nationality?isoAlpha3=,
GET /REST/nationalities/v1/nationality?isoNum3=,
GET /REST/nationalities/v1/nationality?nisNum3=
GET /REST/nationalities/v1/nationalities?referenceDate=
GET /REST/nationalities/v1/history?referenceDate=&isoAlpha3= 

GET /REST/addressCountries/v1/addressCountry?isoAlpha2= ,
GET /REST/addressCountries/v1/addressCountry?isoAlpha3= ,
GET /REST/addressCountries/v1/addressCountry?isoNum3= ,
GET /REST/addressCountries/v1/addressCountry?nisNum3= ,
GET /REST/addressCountries/v1/addressCountries?referenceDate=
GET /REST/addressCountries/v1/history?referenceDate=&isoAlpha3= 

GET /REST/placeCountries/v1/placeCountry?isoAlpha2= ,
GET /REST/placeCountries/v1/placeCountry?isoAlpha3= ,
GET /REST/placeCountries/v1/placeCountry?isoNum3= ,
GET /REST/placeCountries/v1/placeCountry?nisNum3= ,
GET /REST/placeCountries/v1/placeCountries?referenceDate=
GET /REST/placeCountries/v1/history?referenceDate=&isoAlpha3=

## Today in standard vocabulary:
**countryIsoCode**	: Country represented by an ISO 3166-1 alpha-2 code
**countryNisCode**: Country represented by a NIS code
**countryWithHistoryIsoCode**: Country represented by an ISO 3166-1 alpha-2 (current country) or ISO 3166-3 alpha-4 (former country) code.
**geographicName**: A proper noun applied to a spatial object.

## Today in draft vocabulary:
**Country**: A country is a political state, nation, or territory which is controlled. It is often referred to as the land of an individual's birth, residence, or citizenship.
**territory**: Territory can refer to a country or a part of a country (existing or not)
**CountryIsoCode**: The conceptscheme "CountryIsoCode" contains countries represented by an ISO 3166-1 alpha-2 code.
**CountryWithHistoryIsoCode**: The conceptscheme "CountryWithHistoryIsoCode" contains countries represented by an ISO 3166-1 alpha-2 (current country) or ISO 3166-3 alpha-4 (former country) code.
**TerritoryOfAddress**: "ConceptScheme for territories related to addresses. Authorized concepts come from ISO-3166-1 alpha2 (recommended) and from NIS (only in case information regarding territory recognition by the Belgian state is relevant)"
**TerritoryOfNationality**: "ConceptScheme for nationalities. Authorized concepts come from ISO-3166-1 alpha3 (recommended) and from NIS (only in case information regarding territory recognition by the Belgian state is relevant)"
**TerritoryOfPlace**: "ConceptScheme for territories related to places (e.g. place of birth, place of death). Authorized concepts come from ISO-3166-1 alpha2 (recommended) and from NIS (only in case information regarding territory recognition by the Belgian state is relevant)"

## Missing in federal vocabulary:
referenceDate 
isoAlpha2
isoAlpha3
isoNum3
nisNum3

**Comment by pvdbosch** [comment]
Some first (incomplete) feedback:
* I'd merge all APIs into a single one (e.g. /country/v1/ ), which is easier for clients. 
  * you can still group operations with tags and specify permissions (security requirements) per operation
  *  use of the /REST/ prefix isn't a recommendation btw if there's no BOSA-specific reason for it; in REST guide it is only copied from some Smals example API. 
* recommended to support "document archetype" (section 4.3 of REST guide) :
  * e.g. GET /nationalities/{isoAlpha2Code}
  * though not straightforward here, because of the choices between multiple identifiers. Maybe use alpha-2 as primary identifier
* I don't understand the difference between place and address countries here. [Statbel](https://statbel.fgov.be/nl/over-statbel/methodologie/classificaties/landencodes) says that addressCountries are always current countries: "De nuance tussen adres en plaats is dat het adres de actuele toestand is. Bv. Het land van de geboorteplaats bestaat mogelijk vandaag niet meer, dus kan niet als adres gebruikt worden. Bv. Fusie Oost- en West-Duitsland. ". However, the API seems to support former countries for address (using history and referenceData)

**Comment by smals-vea** [comment]
Before validate this API, it will important to have the logical data model and compare this with the swagger file

**Comment by smals-vea** [comment]
**AS IS Statbel:**
https://statbel.fgov.be/fr/propos-de-statbel/methodologie/classifications/codes-pays

Fichier ISO alpha 2: 294 rows
Fichier ISO alpha3: 296 rows
Fichier ISO NUM3: 295 rows
Fichier NIS num3: 320 rows (de 101 à 694 + 999, dont qqs doublons)
Je pensais qu'il y avait une correspondance 1-1 entre ISO alpha2, alpha3 et num3, ce n'est pas le cas, est-ce normal?

Dans le fichier PLACE, 355 rows, dont 27 rows n'ont pas d'ISO alpha2 mais ont un NIS et 34 rows n'ont pas de NIS mais ont un ISO alpha2

Dans le fichier ADDRESS, 273 rows, dont 20 rows n'ont pas d'ISO alpha2 mais ont un NIS et 23 rows n'ont pas de NIS mais ont un ISO alpha2

Dans le fichier NATIONALITIES, 362 rows, dont 2 rows n'ont pas d'ISO alpha3 mais ont un NIS (Kosovo 153, Congo 362) et 1 row n'a pas de NIS mais a un ISO alpha3 (VDR North Vietnam)

**AS IS KSZ/RN/Smals**

Fichier NIS num 3 : 475 rows: 
- 305 rows (de 101 à 694 + 999) dont 67 rows sans iso alpha2
- 170 rows pour des besoins business entre 700 et 995, sans iso alpha2
- pas de doublons 

**TO BE**
Il y a donc une petite vingtaine de codes ISO qui n'ont pas de NIS, si on leur assignait un NIS, on pourrait avoir un identifiant unique NIScode pour identifier les adresses, les historiques et les nationalités.

Qu'en pensez-vous ?

**Comment by pvdbosch** [comment]
> Before validate this API, it will important to have the logical data model and compare this with the swagger file

I agree that the semantics should be clear first:
* statbel semantics differ from ISO standard  (no use of ISO 3166-3 alpha4, distinction address/place, use of alpha3 for nationalities)
* statbel semantics differ from CountryService: there's no concept of historical address countries according to statbel

Then there's also the modelling of mapping ISO<>NIS code:
* statbel lists only one-to-one mapping, but in practice this isn't the case (e.g. NIS code Franse Antillen --> multiple ISO codes for each island)

Only when this is clear, the REST API can be defined with Swagger/OpenAPI 

There are also data quality issues, but they don't need to block the definition of the API.

**Comment by smals-vea** [comment]
Lors de la réunion du 30/07/2021, il a été décidé de valider (**FedVoc Standard**)

- countryIsoAlpha3Code
- countryIsoNum3Code
- countryNisCode

par contre, de laisser en **Draft** en attendant les décisions du groupe de travail des Affaires étrangères (prévu en 09/2021)

- CountryIsoCode 
- CountryWithHistoryIsoCode

@MarcBruyland , peux-tu déplacer le concept countryIsoCode vers Draft ?

Enfin, le concept "referenceDate" ne sera pas ajouté au FedVoc car trop spécifique à un contexte.

**Comment by pvdbosch** [comment]
For CountryIsoCode ( = the alpha 2 code), I don't remember if we discussed it specifically. 
Depending on the outcome of the working group, we may decide to recommend it to use in all international contexts (nationality, address, ...) where a currently existing country is needed by default, rather than the num-3 or alpha-3 equivalents. I think this is why the "Alpha2" wasn't put explicit in the name, but we would consider to rename it to CountryIsoAlpha2Code as well.

**Comment by MarcBruyland** [comment]
New proposal for th REST services:

GET /countries/v1/isoCodes?referenceDate=
GET /countries/v1/nisCodes?referenceDate= 

GET /countries/v1/nationalities?isoAlpha2= ,
GET /countries/v1/nationalities?isoAlpha3=,
GET /countries/v1/nationalities?isoNum3=,
GET /countries/v1/nationalities?nisNum3=
GET /countries/v1/nationalities?referenceDate=
GET /countries/v1/nationalities/history?referenceDate=&isoAlpha3= 

GET /countries/v1/addressCountries?isoAlpha2= ,
GET /countries/v1/addressCountries?isoAlpha3= ,
GET /countries/v1/addressCountries?isoNum3= ,
GET /countries/v1/addressCountries?nisNum3= ,
GET /countries/v1/addressCountries?referenceDate=
GET /countries/v1/addressCountries/history?referenceDate=&isoAlpha3= 

GET /countries/v1/placeCountries?isoAlpha2= ,
GET /countries/v1/placeCountries?isoAlpha3= ,
GET /countries/v1/placeCountries?isoNum3= ,
GET /countries/v1/placeCountries?nisNum3= ,
GET /countries/v1/placeCountries?referenceDate=
GET /countries/v1/placeCountries/history?referenceDate=&isoAlpha3=

**Comment by smals-vea** [comment]
A few comments:

- Pour le nom de l'API, chez Smals, nous préconisons un mot au singulier (et les ressources au pluriel) -> country/v1
- isoAlpha2 ou isoAlpha2Code ?
- nisNum3 -> dans fdvoc on l'a nommé countryNisCode
- je ne remettrai pas le mot 'countries' dans 'addressCountries' et 'placeCountries', vu qu'on est dans l'API country 
- referenceDate n'est pas clair pour moi, reference par rapport à quoi ?
- /history?referenceDate -> chez Smals, nous sommes en train d'établir des guidelines pour cette ressource history que nous soumettrons au WG technical:
"{
 "self": "http://rest-reference.test.paas.socialsecurity.be/REST/demo/v1/employers/93017373/history",
 "items":[
   {
     "href":"/employers/93017373/history/198132654",
     "title":"Belgacom",
     "nssoNumber": 93017373,
     "enterpriseNumber": 202239951
     "fromDate":"1930-07-19T01:00:00Z"
     "toDate":"2014-09-01T00:59:59Z"
   },
   {
     "href":"/employers/93017373/history/917654315",
     "title":"Proximus",
     "nssoNumber": 93017373,
     "enterpriseNumber": 202239951
     "fromDate":"2014-09-01T01:00:00Z"
     "toDate":""
   }
 ],
 "total":2
}
Remarks:
The items in this collection are of the same type as the resource that is the parent of this history, with the exception that they include the "**fromDate**" and "**toDate**" attributes that indicate when this particular entry was active.

Clients can query the history collection with any business attributes deemed relevant, but they can also use the "**date**" query parameter to find the history entry that was active at a given date.

**Comment by pvdbosch** [comment]
I'd leave the "countries" as part of "addressCountries" / "placeCountries", because it'd be confusing to name the resource types being consulted "addresses" or "places". In general an API name is a domain, but may expose different resource types.

For validity period of a resource, maybe we could use a property "validityPeriod" with type "Period" from [belgif-openapi-time](https://github.com/belgif/openapi-time/blob/master/src/main/openapi/time/v1/time-v1.yaml#L24)  ; but we'll wait for discussion in the technical WG then.

**Comment by MarcBruyland** [comment]
Input from my colleague Liesbet D'Hondt wrt **nationality**:

Met nationaliteit wordt bedoeld: de relatie aanduiden tussen een individu en een Staat, cultuur of loyaliteit. Nationaliteit heeft een tweeledige betekenis:
1.	het bezit van het staatsburgerschap van een land of meer landen;
2.	het op grond van herkomst of afstamming behoren tot een bepaalde etniciteit en (indien aanwezig) de natie; nationaliteit staat in deze definitie los van het staatsburgerschap.
 
Bron: [Landencodes | Statbel (fgov.be)](https://statbel.fgov.be/nl/over-statbel/methodologie/classificaties/landencodes)
 
Nog even verder gezocht: deze praktijk is ook volledig in lijn met de ISO 3166-1 standaard:  
“…
In addition, in machine-readable passports, the codes are used to determine the nationality of the userand, when we send money from one bank to another, the country codes are a way to identify where the bank is based.
…” 
https://www.iso.org/iso-3166-country-codes.html 
ISO bepaalt de nationaliteit dus ook op basis van het land met bijhorende landencode.

**Comment by MarcBruyland** [comment]
## Difference between an Address Country and a Place Country ?  
(question raised at the functional wg meeting of 2022-06-28)

See https://statbel.fgov.be/sites/default/files/Over_Statbel_FR/Nomenclaturen/NVcountrycodewhitpaper_nl.pdf
"
Country codes worden gebruikt voor het representeren van het land van een adres, de nationaliteit en het land van een plaats (geboorte- of van overlijden).

**Met land wordt bedoeld**: het territorium van één Staat. Een Staat is de binnen een afgebakend grondgebied werkzame, in hoge mate soevereine organisatie die gezag uitoefent over de op dat grondgebied wonende bevolking, die deze bevolking naar buiten toe vertegenwoordigt en die over de benodigde machtsmiddelen beschikt.

**Met een adres wordt bedoeld**: de aanduiding van een bepaalde locatie, doorgaans van een huis, woning, gebouw of faciliteit. De bekendste vorm is het adres, dat aangeeft waar een persoon woont (het woonadres of domicilie) of verblijft (verblijfadres), waar een bedrijf of rechtspersoon is gevestigd (het vestigingsadres), waar post moet worden bezorgd (het postadres). Het hoogste niveau van detaillering is het land.

**Met nationaliteit wordt bedoeld**: de relatie aanduiden tussen een individu en een Staat, cultuur of loyaliteit. Nationaliteit heeft een tweeledige betekenis:
• het bezit van het staatsburgerschap van een land of meer landen;
• het op grond van herkomst of afstamming behoren tot een bepaalde etniciteit en (indien aanwezig) de natie; nationaliteit staat in deze definitie los van het staatsburgerschap.

**Met plaats wordt bedoeld**: een aanduiding voor een locatie waar zich iets heeft voorgedaan (geboorte of overlijden). Het hoogste niveau van detaillering is het land. 

**De nuance tussen adres en plaats is dat het adres de actuele toestand is. Bv. Het land van de geboorteplaats bestaat mogelijk vandaag niet meer, dus kan niet als adres gebruikt worden. Bv. Fusie Oost en West Duitsland.**
"

**Comment by smals-vea** [comment]
Dag Marc, à quoi sert alors l'historique d'une adresse ? si je comprends quand ça devient "historique" on ne parle plus de "address" mais de "place" ? bvb; Zaire is een "place" ?

**Comment by pvdbosch** [comment]
@MarcBruyland , 

Ik sluit me erbij aan dat dit onderscheid kunstmatig lijkt, en in contradictie met de webservice waarin nog wél gesproken wordt over de historiek van een "adressCountry".

Ik verwijs ook even naar de nota uit #4:

```
De authentieke bron beschrijft drie business contexten:
-	Adres: altijd een ‘actueel’ land
-	Plaats van een gebeurtenis: actueel of historisch
-	Nationaliteit van een persoon: actueel of historisch
Het onderscheid tussen ‘adres’ en ‘plaats’ is verwarrend: een adres kan in praktijk, net zoals nationaliteit of plaats, een historisch of actueel gegeven zijn.
We stellen voor om business contexten opnieuw te formuleren als volgt:
1.	Plaats 
•	kan zowel van een gebeurtenis zijn als onderdeel van een adres
•	indien geen soeverein (independent) land, behoort tot een ander soeverein land dat de nationaliteit van de burgers bepaalt 
•	de context bepaalt of en welke historische landen toegelaten zijn
o	bvb alle landen die bestonden op datum van aangifte van een adres
o	bvb alleen actuele landen bij bepalen adres voor verzending van een brief
2.	Nationaliteit
•	Hier gebruikt in de betekenis van staatsburgerschap
•	alleen soevereine landen toegelaten (in ISO: independent=yes)
•	de context bepaalt of en welke historische landen toegelaten zijn 
```

**Comment by smals-vea** [comment]
@MarcBruyland,
 je suis d'accord que la date est "relevant" mais les pays ci-dessus sont en fait actifs à partir d'une date, et le sont encore. Il ne s'agit donc pas d'historique mais plutôt d'un statut "actif" à la date du ...

**Comment by MarcBruyland** [comment]
As discussed in the federal wg meeting on 2022-09-30:
BOSA is waiting for new xml files from Statbel before starting the development of REST services. Once available, BOSA decided to do an as-is remake in REST.
Attached an analysis of the old xml files is available.
[Country_Services_002.docx](https://github.com/belgif/fedvoc/files/9698191/Country_Services_002.docx)

**Comment by smals-vea** [comment]
@MarcBruyland, 
je propose que l'API REST/country puisse offrir les données telles présentées sur le site Statbel (à savoir plus que 1 seul fichier xls (https://statbel.fgov.be/fr/propos-de-statbel/methodologie/classifications/codes-pays)).
Une revue par le REST Board Smals (avec Peter VDB en plus) serait aussi une garantie de qualité et du respect des Guidelines REST. Le REST Board a la bonne habitude de suggérer une simplification du swagger/API, qui est win-win pour la maintenance évolutive du service.
Qu'en penses-tu ?

**Comment by MarcBruyland** [comment]
Issue closed as decided by the functional wg on 2023-06-09.
Design was approved. Development is ongoing at BOSA.
