### ISSUE TITLE
FedVoc: id 241 cbeNumber to keep or not in FedVoc?

### ISSUE THREAD

**Issue by smals-vea** [belgif/fedvoc#16]
Lors du meeting du 28/05/2021 (https://fedictaim.atlassian.net/wiki/spaces/JCSP/pages/3194782095/2021-05-28+Meeting+notes), avec la présence deMichel Evrard (FOD Economy-KBO), les noms de 
- (Cbe)RegistredEntity et 
- EstablishmentUnit 
seront ajoutés au FedVoc comme une spécification belge pour les RegisteredOrganization et OrganizationUnit.

Ces 2 concepts ont un identifiant reconnus comme enterpriseNumber et etablishmentUnitNumber.

Chez KBO/BCE, il ne semble pas exister de concept générique qui reprendrait toute entité (entreprise ou unité d'établissement) enregistrée chez KBO/BCE.
Ceci sera encore vérifié et confirmé par M. Evrard.

Or, nous avons créé le cbeNumber (id 241) pour permettre à certains business d'invoquer soit une entreprise, soit une unité d'établissement.

@VéroniqueAdam vérifier si ce besoin de "cbeNumber" est réel sur base d'un business use case.

**Comment by pvdbosch** [comment]
EstablishmentUnit would be a specialization of Site rather than OrganizationalUnit.

Site: An office or other premise at which the organization is located.
OrganizationalUnit: An Organization such as a department or support unit which is part of some larger Organization and only has full recognition within the context of that Organization.

**Comment by smals-vea** [comment]
Dans les glossaires généraux et les glossaires spécifiques (donc par business) de Social security, **nous n'avons également que les deux concepts plus spécifiques** et non un concept générique.
Cf. aussi le Portail de la Sécurité sociale : https://www.socialsecurity.be/site_fr/employer/applics/coronavirus/index.html

**Comment by smals-vea** [comment]
En attente d'une confirmation de Michel Evrard (BCE), cf. mail Marc Bruyland du 2/08/2021

**Comment by MarcBruyland** [comment]
cbeNumber will be removed from fedvoc as decided by the functional workgroup on 2021-10-29.

**Comment by MarcBruyland** [comment]
Closure of issue.
