### ISSUE TITLE
FedVoc: id 686 municipalityCode: definition to review

### ISSUE THREAD

**Issue by smals-vea** [belgif/fedvoc#19]
Lors du meeting BCSS: WG Registres du 10/06/2021, V. Turine nous a signalé que le NISCode (donnée changeante) ne sera plus retenu comme identifiant BeSt pour le  municipalityCode.

@MarcBruyland peux-tu adapter la définition dans FedVoc ?

**Comment by MarcBruyland** [comment]
Today the municipalityCode still is the NIS code.
We don't know yet by what it will be replaced and when this replacement will take place.
I propose to wait till things become clear.

**Comment by pvdbosch** [comment]
I guess the alternative would be the full URL representation ("objectId" in fedvoc, like for other BeSt address components) and rename MunicipalityCode to MunicipalityNisCode. But we can wait a bit until it's more certain.

**Comment by smals-vea** [comment]
30/07/2021: le groupe a décidé de ne pas adapter la définition de MunicipalityCode tant que c'est le NIS-code. Le jour où il y aura d'autres valeurs que le NIS Marc adaptera la définition dans FedVoc
