### ISSUE TITLE
coding types: with or without suffix "Code"?

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#2]
ex. 
* Gender vs GenderCode
* Municipality vs MunicipalityCode
* Status vs StatusCode
* Region vs RegionCode
* CivilState vs CivilStateCode

In vocabularies excel and in Swagger.

Impact on:
* clarity: code vs description/label fields
* verbosity in JSON

**Comment by smals-vea** [comment]
I prefer to suffix the name by "Id" or "Code" or "Number" or "Name" to avoid confusing:
- "municipalityName" **is not the same** as "municipalityCode" **and we need the both**
- "region" or "regionName" is not the same as "regionCode"
- in Best Address, they use "streetName", "municipalityName", "postName", "postCode", "municipalityCode", "houseNumber", "boxNumber"
- in CBE, they use "cbeNumber", "enterpriseNumber", ...

**Comment by pvdbosch** [comment]
@MarcBruyland will examine difference property/concept/conceptScheme

I'll propose REST design group to use suffix (e.g. change to GenderCode)

**Comment by MarcBruyland** [comment]
Anomalies detected in our vocabulary document:

ConceptSchemes without corresponding Concept:
Id    | Name | Ontology
701 | CountryNisCode | Location
364 | Nace2008 | Organization
363 | Descent | Person

Data elements with Type Property instead of Concept:
Id | Name | Ontology
269 | addressStatus | Location
300 | positionGeometryMethod | Location
301 | positionSpecification | Location
666 | streetNameStatus | Location
667 | streetNameType | Location
310 | territory | Location
243 | authorization | Organization
230 | endReason | Organization
235 | function | Organization
237 | legalForm | Organization
239 | legalStatus | Organization
242 | organizationType | Organization
682 | quality | Organization
683 | administrativeStatus | Person
329 | civilState | Person
335 | gender | Person
338 | householdRelationType | Person
347 | register | Person

**Comment by pvdbosch** [comment]
CountryNisCode is an alternative for CountryIsoCode, so should be linked to same Concepts I guess.

**Comment by pvdbosch** [comment]
rename to GenderCode OK for REST design WG. Updated this in https://github.com/belgif/openapi-person/commit/915a802f9375148047a01c8df3d8226fb5270012

ConceptScheme in fedvoc should then be renamed as well.

**Comment by smals-vea** [comment]
@MarcBruyland ne faut-il pas aussi adapter le concept "Gender" en "GenderCode" ?

@MarcBruyland pourrais-tu harmoniser les labels et/ou définitions entre Concept et ConceptScheme ?
exmples: countryNisCode, genderCode, positionGeometryMethod, positionSpecification, function, legalStatus, administrativeStatus, register

@MarcBruyland dans streetNameType, tu parles de "see code list" mais tu n'as pas mis l'hyperlink

@MarcBruyland pour les concepts territory, civilState il faut ajouter les concepSchemes Territory, CivilState

@MarcBruyland id366, supprimer les commentaires

**Comment by pvdbosch** [comment]
I wonder why we deviate from some other sources, by having all our coding lists also as "Concept" (aside from ConceptScheme).
Should we rather have them as "property" to be to define them to a Class, rather then Concept?

E.g. VL has geslacht (property) which can be defined on a Persoon and has a range of Geslacht (ConceptScheme)
while FED has gender (Concept) linked to Person and has range of GenderCode

**Comment by MarcBruyland** [comment]
https://www.w3.org/TR/rdf-schema/#ch_range says:
The triple 
**P rdfs:range C**
states that P is an instance of the class [rdf:Property](https://www.w3.org/TR/rdf-schema/#ch_property), that C is an instance of the class [rdfs:Class](https://www.w3.org/TR/rdf-schema/#ch_class) and that the resources denoted by the objects of triples whose predicate is P are instances of the class C.

If we say "gender range GenderCode", we say that gender is an instance of a ConceptScheme, while in fact it is an instance of a Concept (the value is one of the concepts of the conceptscheme, not the entire conceptscheme).

**Comment by barthanssens** [comment]
Or just use the Core Person existing http://publications.europa.eu/resource/authority/human-sex ...

fedv:gender rdfs:domain fedv:Person
fedv:gender rdfs:range skos:Concept

fedv:GenderCodes a skos:ConceptScheme
fedv:male a skos:Concept
fedv:male skos:inScheme fedv:GenderCodes

Then use SHACL to check if the class the gender property points to belongs to the GenderCodes conceptscheme
(but I assume that is meant by the Excel notation listed above)

**Comment by pvdbosch** [comment]
We are currently recommending the ISO-5218 codes. I hadn't seen the EU "human sex" concept scheme yet, but I wonder if it is commonly used; haven't seen it in exchanges yet (even European ones), and its descriptions limit it to the social sciences domain:

https://publications.europa.eu/resource/authority/human-sex/FEMALE

> The concept FEMALE is used for representing the human sexes in the context of interchange of information in the social sciences domain.

@MarcBruyland , @barthanssens , OK I understand now that both "inScheme" and "range" aren't a good fit. It still seems useful to indicate in the Excel which ConceptSchemes are compatible with a specific property. Would that be doable with SHACL (I don't know it very well), or is SHACL always for a specific message or API?

Alternatively, we might define our own relation;  like Marc had originally:
<property> valueInScheme <ConceptScheme>

It wouldn't need to be necessarily restrictive that only that single scheme may be used; multiple schemes could be linked to a single property, e.g.

> nationality valueInScheme CountryNisCode 
> nationality valueInScheme CountryIsoAlpha2Code

**Comment by MarcBruyland** [comment]
Proposal

__AS-IS in fedvoc__:
gender type Concept
GenderCode type ConceptScheme
datamodel:
gender domain Person
gender range Concept
gender valueInScheme GenderCode

__TO-BE in fedvoc__:
gender type *Property*
rest stays the same

__List of data elements with type Concept in fedvoc__ (standard part):
currency
addressStatus
countryIsoAlpha3Code
countryIsoCode
countryIsoNum3Code
countryNisCode
countryWithHistoryIsoCode
positionGeometryMethod
positionSpecification
regionCode
streetNameStatus
streetNameType
endReason
function
legalForm
legalStatus
nace2008
organizationType
civilState
gender
householdRelationType

__Question__
do we rename  these data elements by systematically adding a suffix Code ?
