### ISSUE TITLE
URI's for KBO/BCE 

### ISSUE THREAD

**Issue by MarcBruyland** [belgif/fedvoc#22]
2022-04-25 KBO/BCE:
Les termes retenus sont donc désormais les suivants :
− Entité enregistrée : « CbeRegisteredEntity »
− Unité d’établissement : « CbeEstablishmentUnit »

2022-05-06 KBO/BCE:
OK pour l’utilisation du domaine « org.belgif.be »

Examples of URI:
https://org.belgif.be/id/CbeRegisteredEntity/0671516647
https://org.belgif.be/id/CbeEstablishmentUnit/2127739441

**Comment by smals-vea** [comment]
we must follow the lowerCamelCase:

- /cbeRegisteredEntity/
- /cbeEstablishmentUnit/

**Comment by MarcBruyland** [comment]
There is no precise rule defined for giving a name to a concept in the URI standard [thematic/iceg_uri_standard.md at master · belgif/thematic (github.com)](https://github.com/belgif/thematic/blob/master/URI/iceg_uri_standard.md).
