### ISSUE TITLE
How to refer to location / municipality

### ISSUE THREAD

**Issue by barthanssens** [belgif/fedvoc#24]
(splitted from #23)

What is the recommended way to use fedvoc for location information, e.g. to refer to a municipality?

Furthermore I found some available territory data using skos and terms of the geonames ontology (example [Belgium](https://github.com/belgif/vocab-belgif/blob/master/prod/data/codelist/territory.nt#L292-L312)), is this one way to model it? Yet the question remains with which property I should refer to a municipality modelled in such a way.

**Comment by barthanssens** [comment]
There is a thesaurus REFNIS-2019 (https://vocab.belgif.be/auth?lang=nl) which uses the (Statbel) codes for provinces, municipalities etc (and also includes skos:match to wikidata and geonames)

To be discussed if this is _the_ way to use (IMHO it depends... it is not really a model in the sense that it has a "Municipality" class attached to it. SKOS is (just) a convenient format for various lists and mapping between several other thesauri

**Comment by MarcBruyland** [comment]
Result of the discussion with Sven Lieber (KBR) in the functional wg meeting of 2022-09-30:
The recommended way to refer to a municipality is to use the BEST municipality identifier which consists of a namespace, the NIS code in 5 positions and a version identifier.
