### ISSUE TITLE
modify Excel to align with Swagger

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#3]
In the vocabularies Excel, for terms that are included in Swaggers:
* propose new shorter definition EN column that can be used in Swagger (max length 100-150 characters), move the rest to CommentEn column.
  * adapt the columns with translations in accordance
  * proposition will be put first in this issue for validation before modifying the Excel
* add flag that Swagger definition exists => Marc

For identifiers, blocked by discussion on representation of identifier types. For now, we could for these cases both description and comment in the Comment columns, separated by a newline.

Also add CountryNisCode description (coding scheme)

**Comment by pvdbosch** [comment]
Excel with in first sheet the definitions adapted to be Swagger-compatible:
[FedVoc-Swagger-alignment.xlsx](https://github.com/belgif/fedvoc/files/4531099/FedVoc-Swagger-alignment.xlsx)

Second sheet has data types that are in Swagger but for which definition in FedVoc doesn't exist or is not the same (mostly temporal).

**Comment by smals-vea** [comment]
I review the FR-columns:

**Comment by smals-vea** [comment]
[FedVoc-VEA-Swagger-alignment.xlsx](https://github.com/belgif/fedvoc/files/4545723/FedVoc-VEA-Swagger-alignment.xlsx)

**Comment by pvdbosch** [comment]
thanks for the review. Assigned to Marc to merge the changes (the "VEA" version) into the main vocabularies Excel.

**Comment by MarcBruyland** [comment]
First sheet is in new version of the fedvoc deliverable.
