### ISSUE TITLE
NihdiNumber

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#31]
Proposal (< @smals-vea ) 

* Label FR/Definition : numéro INAMI / numéro d’identification octroyé aux dispensateurs de soins en Belgique dans le cadre de l’assurance maladie obligatoire, entre autres, pour le remboursement des soins fournis aux patients.
* Label NL/Definition  : RIZIV-nummer / het identificatienummer toegekend aan zorgverleners in België in het kader van de verplichte ziekteverzekering, o.a. voor de terugbetaling van zorg verstrekt aan patiënten.
* Name /Definition : nihdiNumber / the identification number that is given to health care workers in Belgium inside the framework of the compulsory health insurance. This includes, among others, the reimbursement the patient’s care.
* Ontology : organization
* Comment FR : Le format est de 8 positions numériques 000000-00 où les 6 premiers digits sont dans le range de valeur 0 à 999999 suivis d’un check digit en 2 positions
* In OpenAPI : yes

My feedback: 
* is the ontology "organization" correct? It identifies a health care worker. Alternatives: "HealthCare", "Employment", "Person".
* I'd just document 8 digits and would drop the documentation about the check digits. The usefulness of check digits to check correctness seem to have been weakened a lot to make more numbers available for use.  There are even four modulo numbers to be taken into account.

"M Het priemgetal dat wordt gebruikt voor de berekening van de modulo: 97, 89, 83 of 79"
from: https://www.riziv.fgov.be/nl/professionals/andere-professionals/softwareleveranciers#:~:text=Hoe%20controleert%20u%20de%20geldigheid%20van%20de%20check%2Ddigit%20%3F

About the OpenAPI type:

Proposal: 

```YAML
NihdiNumber:
  description: Identifier attributed by NIHDI to health care workers in Belgium
  type: string
  pattern: '^\d{8}$'
```
Should we also add the three-digit CompetenceCode / "bevoegdheidscode"?

Repo should be aligned with ontology (person, healthcare, organization, employment)

**Comment by JDMKSZ** [comment]
I think this belongs in a healthcare ontology, its use is restricted to that domain in particular
