### ISSUE TITLE
Mix of datatype IRI and skos thesauri

### ISSUE THREAD

**Issue by barthanssens** [belgif/fedvoc#36]
Fedvoc excel mixes up IRIs for datatypes and SKOS thesauri / code lists

E.g http://vocab.belgif.be/auth/CountryIsoCode, http://vocab.belgif.be/auth/StreetRrnCode

The intention of /auth/ is to have thesauri / code lists etc (see also the EU Publication Office), not to be a catch-all for various unrelated concepts.

Datatypes IRIs should be defined as part of a vocabulary or ontology (/ns)

**Comment by MarcBruyland** [comment]
Will be fixed - see fedvoc meeting of 2024-09-27
