### ISSUE TITLE
Mix of concept scheme IRIs and vocabulary IRIs

### ISSUE THREAD

**Issue by barthanssens** [belgif/fedvoc#37]
Fedvoc excel mixes concept scheme IRIs (which should be '/auth') and vocabulary IRIs ('/ns')

It even contains invalid IRIs like http://vocab.belgif.be/ns/other#naceeurev2#id  (note the fragment '#' being used _twice_) 
and http://vocab.belgif.be/ns/other#function#id

**Comment by MarcBruyland** [comment]
Will be fixed - cfr fedvoc meeting of 2024-09-27
