### ISSUE TITLE
semantics and coding schemes of country 

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#4]
Some problems have been raised with the BE authentic source on country-related semantics (nationality, address, ...) and the practical use and conversion of the ISO alpha-2 codes.

These are described in:

[20190523-Nota landencodes.docx](https://github.com/belgif/fedvoc/files/4529316/20190523-Nota.landencodes.docx)

**Comment by pvdbosch** [comment]
@bertvannuffelen pointed out in https://github.com/belgif/openapi-location/issues/2 that there exists a EU codelist with links between countries "succeeded by" or "preceded by" on https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/country

The EU list seems to be based on a superset of the ISO 3166-1 alpha-3 one, extended by some additional codes for countries predating the ISO-list (from 1950, +/- inception of EU).
Aside from this, it seems to be roughly equivalent to the ISO lists on wikipedia:
* https://en.wikipedia.org/wiki/ISO_3166-1
* https://en.wikipedia.org/wiki/ISO_3166-3

**Comment by smals-vea** [comment]
Lors de la réunion du 30/07/2021, il a été décidé d'attendre la réunion des partenaires Affaires étrangères, KSZ, SPF intérieur, ... qui aura lieu en 09/2021

**Comment by pvdbosch** [comment]
a new version of the [whitepaper](https://statbel.fgov.be/sites/default/files/Over_Statbel_FR/Nomenclaturen/NVcountrycodewhitpaper_nl.pdf) is being drafted by the "Gebruikerscomité Authentieke Bron landencodes"; though not yet sure how far this will address all issues. CBSS representative will discuss the concerns of the note during the next comité (probably November)

**Comment by pvdbosch** [comment]
new version of whitepaper appears to be made available in the meantime: https://statbel.fgov.be/sites/default/files/Over_Statbel_FR/Nomenclaturen/AB_landencodes_whitepaper.pdf

The authentic source now only contains ISO 3166-1 alpha-2 and NIS-codes. The ISO 3166-3 former country codes would be added in an upcoming version. Data quality was improved as well.

Other (less used) ISO codes seem to have been removed. Maybe they can be retrieved from a list managed by ISO or Europe, if needed. 

The contexts of address/place/nationality have been removed as well.  While removing distinction between address and place was proposed in our note, it would still be useful to have an authentic source of which countries can be used in context of nationality (as recognized by Belgium), and residents of which countries (in "place" interpretation) belong to which nationality.
@JDMKSZ will follow this up for the functional WG.

**Comment by pvdbosch** [comment]
Nationalities have been (re-)added to the statbel website: https://statbel.fgov.be/nl/over-statbel/methodologie/classificaties/landencodes

**Comment by pvdbosch** [comment]
I think this issue can be closed now; statbel website, fedvoc and the OpenAPI types are aligned now.

There's still a related issue about citizenship vs nationality, but that might best be handled separately.

**Comment by MarcBruyland** [comment]
Issue can be closed as decided by the functional workgroup on 2024-04-12.
Statbel, fedvoc and OpenAPI types are aligned.
